import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavigationBar from "@/components/kaming/header";
import Background from "@/components/kaming/background";
import Footer from "@/components/kaming/footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Trainity | Your Coding Tutor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <Background>
            <NavigationBar />
            {children}
            <Footer />
        </Background>

      </body>
    </html>
  );
}